Repository ZeusWPI/zauth, pull requests merged in 2021-10, with the labels that each got.

#139 Fix creating a new user for admins
  templates/users/new_user.html
Labels: bug

#142 Update last_login when user logs in
  src/controllers/sessions_controller.rs
  src/models/user.rs
Labels: feature

#122 Change registration flow to confirm email first
  migrations/2021-09-25-224437_change_registration_flow/down.sql
  migrations/2021-09-25-224437_change_registration_flow/up.sql
  src/controllers/users_controller.rs
  src/models/user.rs
  templates/mails/confirm_user_registration.txt
  templates/mails/user_approved.txt
  templates/users/confirm_email_success.html
  tests/common/mod.rs
  tests/users.rs
Labels: feature

#148 Fix compilation error introduced by merges
  src/controllers/users_controller.rs
Labels: bug

#149 Show errors in reset password form
  src/controllers/users_controller.rs
  templates/users/reset_password_form.html
Labels: bug

#151 Add NPM to flake to make compiling the CSS possible
  flake.nix
Labels: chore

#150 Add password manger recommendation to registration from
  templates/users/registration_form.html
  templates/users/reset_password_form.html
Labels: feature

#152 Fix compiler warnings and check token endpoint more thoroughly
  src/controllers/oauth_controller.rs
  src/controllers/pages_controller.rs
  src/ephemeral/session.rs
  src/errors.rs
Labels: chore

#153 Don't send email address in /current_user endpoint
  src/models/user.rs
Labels: bug
