Repository ZeusWPI/zauth, pull requests merged in 2022-06, with the labels that each got.

#178 catch unique constraint violations when creating users
  src/models/user.rs
  tests/users.rs
Labels: bug

#189 Some maintenance work
  Cargo.lock
  Cargo.toml
  flake.lock
  src/views/accepter.rs
Labels: chore

#199 Fix grant toggle not being saved when toggled.
  src/controllers/clients_controller.rs
  src/ephemeral/from_api.rs
  src/models/client.rs
  templates/clients/edit_client.html
  tests/clients.rs
Labels: bug

#201 Fix needs grant always being overridden
  src/controllers/clients_controller.rs
  templates/clients/edit_client.html
  tests/clients.rs
Labels: bug

#202 Show Zauth version in footer
  src/lib.rs
  src/views/template.rs
  templates/layout.html
Labels: feature
